### ISSUE TITLE
Compiled pdf all-bold when compiling with TexLive version 2022

### ISSUE THREAD

**Issue by fairuzishraque** [treyhunner/resume#8]
Regardless of the contents of the .tex file, when the pdf is compiled with TexLive 2022, all of the text is bold.
[output.log](https://github.com/treyhunner/resume/files/9677737/output.log)

**Comment by ghost** [comment]
I also encountered this issue. The easy fix I found was to wrap `bf #1` with another pair of braces on line 84 of `resume.cls` as so:

```latex
  \MakeUppercase{{\bf #1}}
```

**Comment by jasperhabicht** [comment]
A correct solution would be not to use the deprecated `\bf` (and `\em`) command at all and change line 84 (of the .cls file) to:

```diff
-  \MakeUppercase{\bf #1}
+  \textbf{\MakeUppercase{#1}}
```

Line 60 should be changed to:

```diff
-    \hfil{\MakeUppercase{\namesize\bf \@name}}\hfil
+    \hfil{\textbf{\MakeUppercase{\namesize\@name}}}\hfil 
```

And line 101 should be changed to:

```diff
-   {\bf #1}                 \hfill                  {    #2}% Stop a space
+   \textbf{#1}              \hfill                  {    #2}% Stop a space
```

Finally, line 104 should be changed to:

```diff
-   {\em #3}                 \hfill                  {\em #4}% Stop a space
+   \emph{#3}                \hfill                  \emph{#4}% Stop a space

**Comment by victorhartman** [comment]
@jasperhabicht you should make a pull request to implement these changes! I can also do it, if you don't want to.

**Comment by jasperhabicht** [comment]
@VictorHartman Feel free to do it! I was not sure whether this project is still being actively managed. I opened another issue which should probably implemented as well.
