### ISSUE TITLE
Use \AtBeginDocument instead of redefining \document

### ISSUE THREAD

**Issue by jasperhabicht** [treyhunner/resume#9]
Redefining the `\document` macro is not a good idea, because this can easily mess up the code when other packages are used. It is far more reliable to use `\AtBeginDocument` to insert code directly after `\begin{document}`. I therefore suggest that lines 68 to 76 in the .cls file are replaced as follows: 

```diff
- \let\ori@document=\document
- \renewcommand{\document}{
-   \ori@document                     % Begin document
+ \AtBeginDocument{
    \printname                        % Print the name specified with \name
    \@ifundefined{@addressone}{}{     % Print the first address if specified
      \printaddress{\@addressone}}
    \@ifundefined{@addresstwo}{}{     % Print the second address if specified
      \printaddress{\@addresstwo}} 
  }
```

**Comment by passos** [comment]
I noticed that there is a warning regard to document command when use it like `\begin{document}`. The message is `Overfull \hbox (30.0pt too wide) in paragraph at lines 11--11 []`. Do you have any idea how to fix it?

Version: Latexmk, John Collins, 17 Mar. 2022. Version 4.77, version: 4.77

**Comment by jasperhabicht** [comment]
@passos This is true, but it has nothing to do with this issue. If you keep the original code, the same warning appears. Maybe open a new issue?

**Comment by treyhunner** [comment]
Added in #10
